### ISSUE TITLE
ToDo: Sep 2014 Board Report

### ISSUE THREAD

**Issue by shazron** [cordova/apache-board-reports#2]
- [x] Prepare report for Sep based on 3.6.0 or greater Vote Results since last report
- [x] Prepare report stats, included cordova download stats from NPM
- [x] Prepare report for any new committers/PMC members since last report
- [x] Prepare report for any challenges since last report
- [x] Prepare report for any plugin/tool releases since last report (ongoing as it happens)
